nucleotide_dic = {"A": "T", "T": "A", "G":"C", "C":"G"}


def complement(DNA):
    """Return complement of DNA string"""
    complement = []
    for nuc in DNA:
        complement.append(nucleotide_dic[nuc])
    return "".join(complement)


def reverseComplement(DNA):
    """Print reverse complement of DNA string"""
    complement_DNA = complement(DNA)
    # Print de reverse complement
    print(complement_DNA[::-1])
    

if __name__ == "__main__":
    DNA = "ATATCTGCTTGGGTCCAGGTGAAGCTGTAGCCCTTATTTCTCGAAGGTGGCGTGACCTCAGGAGCATAAGGGTCGCCGTGCAAGGACGCAATGCGGTTTAATTTAACGATTCCAGACAAGGCATTCAAAACAGGCGGATGGCAAAAGGGTGAGTCCGTCAGCGACTCTAGTCTCGTCCTTCACGATTTTAATGGCTCCCCCAGCCGGGCCCATTGCCCAGAAGCCTCTCCAACACCGGTGGAAAAGGGTTCTGTAATTCCGTTATTCTGGTGTACATAACGTAGACTCATTGCGATTACATGGTGCATTGACCCGTTGTAGTGTACAGAATGATAACGGATGCTTTGATCCTTTCGGGGTTCACGAGGGGCAACATGTGCTTTCGTCGGTATACGTGGCTGATCGAACCAATCCACGAGCGGTACCTCATCGCACAAGATAGGCCGAGTATCCAGGCTAAAATGGCAGATAGGAACTCCACCCATCTCCGCCCGTGTGAATTACTCGCCGGCTCCCCCCGATAAACACGGTGGTGCCTTCAGCGAGTAGATCTCGGTAGCGAAGCTGAACGGGAGAAGCACATGCCATGGCGGGCACGCCCAGTGCCCACGCGAGCCATCATTACAAGATGATGTTGCGTTAGTAGTACGATAGTTCGACCTACCGGCCCAGGTTTCCATGCTGCTTGGACTCTTCGCACTTATTTGAGTCTCTGGGGCCTGTGGTGCTTCATCGCTTTGCAGCATCTCGCGCAGGCCAATGTCATGCTACTGAAAATTACCGAAAGGTGATAGCCACACCTCTGGCAATCCTTCGTACGCGCGTACTTCACCAAGGTTTAGAGAGTTATA"
    reverseComplement(DNA)
