def countNucleotides(DNA):
    """Count all DNA nucleotides and print the number of A, T, G and C"""
    numA = DNA.count("A")
    numC = DNA.count("C")
    numG = DNA.count("G")
    numT = DNA.count("T")
    print(numA, numC, numG, numT)


if __name__ == "__main__":
    DNA = "GACCCGCTTTCGATGAGTATATACGATTAGTGCAGTGTAGTCCGGTCAGATAATAGGCAGATTAGTCGCGTCACAGATACTGGTGCCTCTGAACGAGGGCTATACTGGTCCTGCGTCCCTGCCGCCACCGTTTTCGCATAAGTGACGAACACCGTTATTAGTTCGACCAGATCATAAGATAACTCAAAATTACTCTCCGCTTGCTGGGTTTCCCGCGAGCTAGCAGTTTCTTATAGAATCAATCGACACTCAGCTGCCGAGAGAGCGTGAAGATCGCTTATGGCGTTGATTGGTGTACAGCGTTAGGTAGATTTCGGGATTTGGGGGTAAGGCTTACTTTATGTCCGCGTGGTAAGCAAAAACCTGCTTGGATCCGCCCGGATTCCTTGAATCGTGCGATAAAAGAACTATAGGATTCATCAACCGAGATATAGATCGTCCTAGTAGCGGGCCCGACTCGCGAGATTGTGAATTTTTGGCTTAAAACGACGTCGGTTGCAACTCTAATATTATATTCTATTCGCTACAGCGCACTTCTATCCTACCTAGTCACTGACGAGCTTAATCCTAACCAACTCTCATCGATCGACCACAAAATCCGATAACAAACTATTCAAGGCATTTGTGAATGACCAGAGGCTACGTGCCATGGTATAGAACGTGAAGACGTTCACCTCACTTTATAGTCTTTGAATTCCAGCGAAAGCGCACCTTCTATGCTAATTCGGCAGAACTATACAAGGGGGCGATCTGGCATAATTTTTATTCAACTGAGCCCAGCGACGTACGCGCCCAGCCACTGTTAACCCTAGACCGAGAGAGTTATACATTGCGTGTTGTAATTACTAGTCATGTCCAATAGTCGGCCTCATGGATGCTCGTT"
    countNucleotides(DNA)